#!/bin/sh
#
# ltd-sync-admin -- Runs `register.py admin` (with sudo) to control our syncing.
#
# Run it as yourself; it calls sudo, so you need sudo rights on this box.
#
# The "$@" will add any arguments to the register.py command's args.
#
DIR=/opt/langtechdepot
sudo python3 $DIR/register.py admin "$@"
